### ISSUE TITLE
Updating brew could be optional

### ISSUE THREAD

**Issue by amadeu01** [bitrise-steplib/steps-brew-install#12]
Updating brew could be optional.
Also, then there is no log option set, we could use `--quiet` to avoid a lot of output.
https://github.com/bitrise-steplib/steps-brew-install/blob/f307d278e39a32b2301b6a4fcb03b977c1561d63/main.go#L93

**Comment by bitce** [comment]
Thanks @amadeu01! Noted this as a feature request, if this is critical for anyone feel free to submit a PR with the changes!

**Comment by adborbas** [comment]
Hi @amadeu01, the above-mentioned PR should have addressed your request. Let us know if you think otherwise.
