### ISSUE TITLE
Step tries to brew cleanup then fails

### ISSUE THREAD

**Issue by franciscarriere** [bitrise-steplib/steps-brew-install#16]
Using the `Install Github CLI` step, the step fails when it tries to brew cleanup.

> +------------------------------------------------------------------------------+
> 
> | (3) Install GitHub CLI                                                       |
> +------------------------------------------------------------------------------+
> | id: brew-install                                                             |
> | version: 0.11.0                                                              |
> | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
> | toolkit: go                                                                  |
> | time: 2020-10-23T16:25:52Z                                                   |
> +------------------------------------------------------------------------------+
> |                                                                              |
> Configs:
> - Packages: hub
> - Options: 
> - Upgrade: true
> - CacheEnabled: false
> - VerboseLog: true
> Run brew command
> $ brew "reinstall" "-v" "hub"
> ==> Downloading https://homebrew.bintray.com/bottles/hub-2.14.2.catalina.bottle.tar.gz
> ==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/fdf05855839a9d7ec6e7bee6796e3cb5fc473500cffc002366cf98c09a805b69?response-content-disposition=attachment%3Bfilename%3D%22hub-2.14.2.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZmRmMDU4NTU4MzlhOWQ3ZWM2ZTdiZWU2Nzk2ZTNjYjVmYzQ3MzUwMGNmZmMwMDIzNjZjZjk4YzA5YTgwNWI2OT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmh1Yi0yLjE0LjIuY2F0YWxpbmEuYm90dGxlLnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYwMzQ3MTA3N30sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=mAY4vi~CoPNsdzMMVJmTWgbCgGBEQcDhNW-~HRWBCXuBcVPQ0Xh6Biu37ykWBZGml0MW7C91GgzmkxvJvFLIeG8bAaev46yLtRRBcVdlFw4znM9nYMNfIeYazXdOZbjzLIs13JzJZ80vpW6CVMLj-hYx-YcMl~X6rZPxMsqVvfgBHXVn03O3rIkFyLA8583tEGX3Dh-q-0HbHtQVLEbc0Jwr34t2Ekgn4UivFruYZhG-zEEcBVof07XlzyvG3tBpkbq3DO6N161kuNeRH7aRXfWjF2rMlD-DEVN4560iNEA16rUQgzQyKrKYh~OHPw6pGvvUnpkdxenwJYQlaOvRAQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
> /usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --header Accept-Language:\ en --fail --silent --retry 3 --location --remote-time --continue-at 0 --output /Users/vagrant/Library/Caches/Homebrew/downloads/2e347e5ac426558bd706e071f55585acddf3a7878f2d6a878246c0187dd78d99--hub-2.14.2.catalina.bottle.tar.gz.incomplete https://d29vzk4ow07wi7.cloudfront.net/fdf05855839a9d7ec6e7bee6796e3cb5fc473500cffc002366cf98c09a805b69\?response-content-disposition=attachment\%3Bfilename\%3D\%22hub-2.14.2.catalina.bottle.tar.gz\%22\&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZmRmMDU4NTU4MzlhOWQ3ZWM2ZTdiZWU2Nzk2ZTNjYjVmYzQ3MzUwMGNmZmMwMDIzNjZjZjk4YzA5YTgwNWI2OT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmh1Yi0yLjE0LjIuY2F0YWxpbmEuYm90dGxlLnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYwMzQ3MTA3N30sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_\&Signature=mAY4vi\~CoPNsdzMMVJmTWgbCgGBEQcDhNW-\~HRWBCXuBcVPQ0Xh6Biu37ykWBZGml0MW7C91GgzmkxvJvFLIeG8bAaev46yLtRRBcVdlFw4znM9nYMNfIeYazXdOZbjzLIs13JzJZ80vpW6CVMLj-hYx-YcMl\~X6rZPxMsqVvfgBHXVn03O3rIkFyLA8583tEGX3Dh-q-0HbHtQVLEbc0Jwr34t2Ekgn4UivFruYZhG-zEEcBVof07XlzyvG3tBpkbq3DO6N161kuNeRH7aRXfWjF2rMlD-DEVN4560iNEA16rUQgzQyKrKYh\~OHPw6pGvvUnpkdxenwJYQlaOvRAQ__\&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
> ==> Verifying 2e347e5ac426558bd706e071f55585acddf3a7878f2d6a878246c0187dd78d99--hub-2.14.2.catalina.bottle.tar.gz checksum
> ==> Reinstalling hub 
> ==> Pouring hub-2.14.2.catalina.bottle.tar.gz
> tar xof /Users/vagrant/Library/Caches/Homebrew/downloads/2e347e5ac426558bd706e071f55585acddf3a7878f2d6a878246c0187dd78d99--hub-2.14.2.catalina.bottle.tar.gz -C /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20201023-1508-1f1j0ql
> cp -pR /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20201023-1508-1f1j0ql/hub/. /usr/local/Cellar/hub
> chmod -Rf +w /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20201023-1508-1f1j0ql
> ==> Finishing up
> ln -s ../../Cellar/hub/2.14.2/etc/bash_completion.d/hub.bash_completion.sh hub.bash_completion.sh
> ln -s ../Cellar/hub/2.14.2/bin/hub hub
> ln -s ../../Cellar/hub/2.14.2/share/doc/hub-doc hub-doc
> ln -s ../../../Cellar/hub/2.14.2/share/fish/vendor_completions.d/hub.fish hub.fish
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-alias.1 hub-alias.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-am.1 hub-am.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-api.1 hub-api.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-apply.1 hub-apply.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-browse.1 hub-browse.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-checkout.1 hub-checkout.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-cherry-pick.1 hub-cherry-pick.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-ci-status.1 hub-ci-status.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-clone.1 hub-clone.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-compare.1 hub-compare.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-create.1 hub-create.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-delete.1 hub-delete.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-fetch.1 hub-fetch.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-fork.1 hub-fork.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-gist.1 hub-gist.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-help.1 hub-help.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-init.1 hub-init.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-issue.1 hub-issue.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-merge.1 hub-merge.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-pr.1 hub-pr.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-pull-request.1 hub-pull-request.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-push.1 hub-push.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-release.1 hub-release.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-remote.1 hub-remote.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-submodule.1 hub-submodule.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub-sync.1 hub-sync.1
> ln -s ../../../Cellar/hub/2.14.2/share/man/man1/hub.1 hub.1
> ln -s ../Cellar/hub/2.14.2/share/vim vim
> ln -s ../../../Cellar/hub/2.14.2/share/zsh/site-functions/_hub _hub
> /usr/bin/sandbox-exec -f /private/tmp/homebrew20201023-1647-1rzfqe3.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hub.rb
> ==> Caveats
> Bash completion has been installed to:
>   /usr/local/etc/bash_completion.d
> zsh completions have been installed to:
>   /usr/local/share/zsh/site-functions
> ==> Summary
> 🍺  /usr/local/Cellar/hub/2.14.2: 64 files, 9.4MB
> ==> `brew cleanup` has not been run in 30 days, running now...
> Removing: /usr/local/Cellar/freetype/2.10.1... (61 files, 2.2MB)
> Removing: /usr/local/Cellar/gdbm/1.18.1... (20 files, 602.8KB)
> Removing: /usr/local/Cellar/gettext/0.20.2_1... (1,923 files, 18.6MB)
> Removing: /usr/local/Cellar/ghostscript/9.52... (671 files, 87.4MB)
> Removing: /usr/local/Cellar/gnu-getopt/2.35.1... (10 files, 163.9KB)
> Removing: /usr/local/Cellar/ilmbase/2.5.1... (87 files, 1.6MB)
> Removing: /usr/local/Cellar/libde265/1.0.5... (22 files, 2MB)
> Removing: /usr/local/Cellar/libomp/10.0.0... (9 files, 1.3MB)
> Removing: /usr/local/Cellar/libtool/2.4.6_1... (71 files, 3.7MB)
> Removing: /usr/local/Cellar/little-cms2/2.9... (18 files, 1MB)
> Removing: /usr/local/Cellar/openexr/2.5.1... (152 files, 6.6MB)
> Removing: /usr/local/Cellar/openssl@1.1/1.1.1g... (8,059 files, 18MB)
> Error: Could not remove python keg! Do so manually:
>   sudo rm -rf /usr/local/Cellar/python/3.7.7
> Removing: /usr/local/Cellar/python/3.7.7... (863 files, 11.7MB)
> Can't install formulas:  exit status 1
> |                                                                              |
> +---+---------------------------------------------------------------+----------+
> | x | Install GitHub CLI (exit code: 1)                             | 19.23 sec|
> +---+---------------------------------------------------------------+----------+
> | Issue tracker: https://github.com/bitrise-steplib/steps-brew-install/issues  |
> | Source: https://github.com/bitrise-steplib/steps-brew-install                |
> +---+---------------------------------------------------------------+----------+

**Comment by maxcnunes** [comment]
I got the same issue:
<img width="835" alt="Screen Shot 2020-10-23 at 16 55 22" src="https://user-images.githubusercontent.com/680356/97048312-98cbeb80-1550-11eb-9443-f29117ceb257.png">

I tried running a new build with remote access and deleting that manually hoping it would do the trick for the other builds, but the next build after that fails again for the same issue.

**Comment by MarcoF09** [comment]
I'm having the same problem, If I use the build with remote access and delete de python folder as commented by @maxcnunes it works but it's not a maintainable solution to future builds. 
I tried also to downgrade of version but It also fails. 
Any update about that fail? Thanks!

**Comment by franciscarriere** [comment]
Just tried it this morning and it seems resolved, without the Remote access workaround.

**Comment by MarcoF09** [comment]
The same on my end, thanks!
