### ISSUE TITLE
Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed

### ISSUE THREAD

**Issue by Ewg777** [bitrise-steplib/steps-brew-install#20]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.11.1
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Running brew "install" "librsvg" almost always fails with the Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed

### Bitrise info

- Build URL: https://app.bitrise.io/build/eb673eebb14f72da
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES /
- Log: 
- +------------------------------------------------------------------------------+

| (5) brew-install@0                                                           |
+------------------------------------------------------------------------------+
| id: brew-install                                                             |
| version: 0.11.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-06-02T05:28:36Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- Packages: librsvg
- Options: 
- Upgrade: false
- CacheEnabled: true
- VerboseLog: false
Run brew command
$ brew "install" "librsvg"
Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install
You can try to install from source with:
  brew install --build-from-source python@3.9
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
Can't install formulas:  exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | brew-install@0 (exit code: 1)                                 | 41.87 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-brew-install/issues  |
| Source: https://github.com/bitrise-steplib/steps-brew-install                |
+---+---------------------------------------------------------------+----------+

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. brew "install" "librsvg"

**Comment by bitce** [comment]
Hi @Ewg777, thanks for your report! This was due to a problem with the system image, should be fixed by now, but let me know if you experience this otherwise.
