### ISSUE TITLE
No update

### ISSUE THREAD

**Issue by yonaskolb** [bitrise-steplib/steps-brew-install#9]
It would be nice to have a built in way to suppress brew from updating itself, which is controlled with the `HOMEBREW_NO_AUTO_UPDATE=1` env. This would speed up the step considerably

**Comment by yonaskolb** [comment]
From looking at the code it looks like `brew update` is called explicitly. Would be good to have a way to suppress that explicit update as well as the implicit update when running `brew install`

**Comment by ahvth-bitrise** [comment]
Hi there @yonaskolb! 👋 I believe the logic behind running the brew update is to ensure that we can reproduce the package versions that get pulled. That said, this sounds like a good option to have, but this would definitely fall into feature request territory.

Could I ask you to please check out our [feature requests subforum](https://discuss.bitrise.io/c/feature-request) and vote for any existing request on the topic or submit a new one? That would currently be the best channel for submitting this.

Thanks for your contribution! 😄

**Comment by andr3a88** [comment]
same here, +1

**Comment by adborbas** [comment]
Hi @yonaskolb , the above-mentioned PR should have addressed your request. Let us know if you think otherwise.
